routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Route::prefix('poll')->name('poll_')->middleware('pc.only')->group(function () {
    Route::get('depression', 'PollDepressionController@poll_view')->name('view');
    Route::post('depression/send', 'PollDepressionController@poll_send')->name('send');

    Route::middleware('tester')->group(function () {
        Route::get('pum', 'PollPumController@poll_view')->name('pum_view');
        Route::post('pum/send', 'PollPumController@poll_send')->name('pum_send');
        Route::get('personal_data', 'PollPersonalDataController@poll_view')->name('personal_data_view');
        Route::post('personal_data/send', 'PollPersonalDataController@poll_send')->name('personal_data_send');
    });
});

Route::prefix('test')->name('test.')->middleware('tester')->group(function () {
    Route::post('save', 'TestResultController@save')->name('save');
    Route::get('next', 'TestResultController@next')->name('next');
    Route::get('finish', 'TestResultController@finish')->name('finish');
});

Auth::routes(['register' => false]);

Route::prefix('auth')->name('auth.')->middleware('auth')->group(function () {
    Route::get('home', 'AdminController@home')->name('home');
    Route::prefix('tests')->name('tests.')->group(function () {
        Route::get('objects', 'AdminController@objects')->name('objects');
        Route::get('objects/ganja', 'AdminController@objects_ganja')->name('objects_ganja');
        Route::get('object/result/{id}', 'AdminController@objectResult')->name('object.result');
        Route::get('objects/results/download', 'AdminController@resultsDownload')->name('objects.results.download');
    });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app" class="h-100">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a style="color:red" class="nav-link" target="_blank" href="https://redtm.pl">Created by {{ __('RedTM.pl') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Logowanie') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Rejestracja') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('auth.home') }}">
                                        Home
                                    </a>
                                    <a class="dropdown-item" href="{{ route('auth.tests.objects') }}">
                                        {{ __('Wyniki obiektów testowych') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('auth.tests.objects_ganja') }}">
                                        Wyniki ganja
                                    </a>
                                    <a class="dropdown-item" href="{{ route('auth.tests.objects.results.download') }}">
                                        Pobierz wyniki
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Wyloguj się') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 h-75">
            @yield('content')
        </main>
    </div>
</body>

<!-- Scripts -->
<script src="{{ mix('js/app.js') }}"></script>
@yield('javascript')
</html>